server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:~/todoDB;DB_CLOSE_ON_EXIT=FALSE;
    platform: h2
    username: sa
    password:
    driver: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true

